/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * You have a DEAL! Backend -> Sender Backend -> Receiver
 */
export interface ShipmentConfirmation { 
    sender: string;
    receiver: string;
    box: string;
    /**
     * An enumeration.
     */
    size: string;
    dropoff_date: string;
    pickup_date: string;
}

